package com.consultar.entidade;
// Generated 31/03/2017 19:48:10 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.List;

/**
 * BairroRepositorio generated by hbm2java
 */
@Entity
@Table(name="bairro"
    ,catalog="consultar"
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")

public class Bairro  implements java.io.Serializable {

    @Id
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "bairro_id_seq")
    @SequenceGenerator(
            name = "bairro_id_seq",
            sequenceName = "bairro_id_seq",
            allocationSize = 1)//de quanto em quanto ele incrementa

    @Column(name = "id")

     private Integer idbairro;
    @NotNull
    @Column(name = "nome")
     private String nome;
    @NotNull
    @Column(name = "status")
     private Integer status;
    @NotNull

    @ManyToOne
    @JoinColumn(name="cidade_id")
     private Cidade cidade;


    @OneToMany(mappedBy = "bairro", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private List<Localizacao> localizacao;

    public Bairro(String nome, Integer status, Cidade cidade, List<Localizacao> localizacao) {
        this.setNome(nome);
        this.setStatus(status);
        this.setCidade(cidade);
        this.setLocalizacao(localizacao);
    }


    public Integer getIdbairro() {
        return idbairro;
    }

    public void setIdbairro(Integer idbairro) {
        this.idbairro = idbairro;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Cidade getCidade() {
        return cidade;
    }

    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

    public List<Localizacao> getLocalizacao() {
        return localizacao;
    }

    public void setLocalizacao(List<Localizacao> localizacao) {
        this.localizacao = localizacao;
    }
}


